/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Operation;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-03-25T11:59:58.075Z")

@Api(value = "account", description = "the account API")
public interface AccountApi {

    @ApiOperation(value = "Get the last operations on your account", nickname = "operations", notes = "Get the last operations on your account", response = Operation.class, responseContainer = "List", tags={ "account", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Operation.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid account number") })
    @RequestMapping(value = "/account/operations",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Operation>> operations(@NotNull @ApiParam(value = "The account number", required = true) @Valid @RequestParam(value = "account", required = true) String account);

}
